name: Deploy to EC2

on:
  push:
    branches:
      - main  # I see you're on master branch from the prompt
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install SSH key
      uses: webfactory/ssh-agent@v0.5.4
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    - name: Configure SSH
      run: |
        mkdir -p ~/.ssh
        chmod 700 ~/.ssh
        echo -e "Host *\n\tStrictHostKeyChecking no\n\tUserKnownHostsFile=/dev/null\n" > ~/.ssh/config
        chmod 600 ~/.ssh/config

    - name: Debug SSH Key
      run: ssh-add -l

    - name: Deploy to EC2
      run: |
        echo "Starting deployment..."
        scp index.html ubuntu@ec2-3-70-223-49.eu-central-1.compute.amazonaws.com:/tmp/index.html
        ssh ubuntu@ec2-3-70-223-49.eu-central-1.compute.amazonaws.com '
          sudo mv /tmp/index.html /usr/share/nginx/html/index.html
          sudo chown www-data:www-data /usr/share/nginx/html/index.html
          sudo chmod 644 /usr/share/nginx/html/index.html
          sudo systemctl reload nginx
          echo "Deployment completed successfully"
        '


