name: Deploy to EC2
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3  # Update to v3
      
    - name: Deploy to EC2
      env:
        PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
        HOST: ${{ secrets.EC2_HOST }}
        USER: ${{ secrets.EC2_USER }}
      run: |
        # Store private key with better security
        install -m 600 /dev/null private_key.pem
        echo "$PRIVATE_KEY" > private_key.pem
        
        # Add error handling
        if ! scp -o StrictHostKeyChecking=no -i private_key.pem index.html ${USER}@${HOST}:~/; then
          echo "Failed to copy file to EC2"
          exit 1
        fi
        
        # Add error checking for deployment steps
        if ! ssh -o StrictHostKeyChecking=no -i private_key.pem ${USER}@${HOST} '
          sudo mv ~/index.html /usr/share/nginx/html/ &&
          sudo chown nginx:nginx /usr/share/nginx/html/index.html &&
          sudo chmod 644 /usr/share/nginx/html/index.html &&
          sudo systemctl restart nginx
        '; then
          echo "Failed to deploy on EC2"
          exit 1
        fi
        
        # Secure cleanup
        shred -u private_key.pem


