name: Deploy to EC2

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Debug Environment
      run: |
        echo "Debugging environment variables (safely)"
        echo "EC2_HOST exists: ${{ secrets.EC2_HOST != '' }}"
        echo "EC2_USER exists: ${{ secrets.EC2_USER != '' }}"
        echo "EC2_SSH_KEY exists: ${{ secrets.EC2_SSH_KEY != '' }}"

    - name: Install SSH key
      uses: webfactory/ssh-agent@v0.5.4
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    - name: Setup SSH directory
      run: |
        mkdir -p ~/.ssh
        chmod 700 ~/.ssh
        touch ~/.ssh/known_hosts
        chmod 644 ~/.ssh/known_hosts

    - name: Add EC2 to known hosts
      run: |
        if [ -z "${{ secrets.EC2_HOST }}" ]; then
          echo "Error: EC2_HOST secret is not set"
          exit 1
        fi
        ssh-keyscan -H "${{ secrets.EC2_HOST }}" >> ~/.ssh/known_hosts || echo "Failed to scan host key"
