name: Deploy to EC2

on:
  push:
    branches:
      - main  # or your default branch name

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Deploy to EC2
      env:
        PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
        HOST: ${{ secrets.EC2_HOST }}
        USER: ${{ secrets.EC2_USER }}
      run: |
        # Store private key
        echo "$PRIVATE_KEY" > private_key.pem
        chmod 600 private_key.pem
        
        # Deploy using SSH
        scp -o StrictHostKeyChecking=no -i private_key.pem index.html ${USER}@${HOST}:/var/www/html/
        
        # Optional: Restart web server if needed
        ssh -o StrictHostKeyChecking=no -i private_key.pem ${USER}@${HOST} 'sudo systemctl restart apache2'
        
        # Clean up
        rm -f private_key.pem

