name: Deploy Static Website to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up SSH keys
      - name: Set up SSH keys
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_SSH_PRIVATE_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          ssh-keyscan -H ${{ secrets.EC2_PUBLIC_IP }} >> ~/.ssh/known_hosts
        env:
          DEPLOY_SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_SSH_PRIVATE_KEY }}
          EC2_PUBLIC_IP: ${{ secrets.EC2_PUBLIC_IP }}

      # Step 3: Deploy static files to EC2
      - name: Copy files to EC2
        run: |
          rsync -avz --delete ./dist/ ${{ secrets.EC2_USER }}@${{ secrets.EC2_PUBLIC_IP }}:/var/www/html/
        env:
          EC2_USER: ${{ secrets.EC2_USER }}
          EC2_PUBLIC_IP: ${{ secrets.EC2_PUBLIC_IP }}

      # Step 4: Restart the web server (if applicable)
      - name: Restart web server (optional)
        run: |
          ssh -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_PUBLIC_IP }} "sudo systemctl restart apache2"
        env:
          EC2_USER: ${{ secrets.EC2_USER }}
          EC2_PUBLIC_IP: ${{ secrets.EC2_PUBLIC_IP }}

